name: Build and publish container

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # 1am every Sunday
    - cron: "0 1 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
  strategy: 
    matrix:
      node-version: [22.x]
    
  steps:
      
    # checkout repo
    - name: Checkout repo
      uses: actions/checkout@v4

    # login in to GitHub Container registry
    - name: Login to GitHub Container registry
      uses: docker/login-action@v1
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        registry: ghcr.io
        username: $GITHUB_USER
        password: ${{ secrets.GITHUB_TOKEN }}

    # build /release/*.js files from /src/*.ts 
    - name: Build node solution release
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      run: npm install
      run: node --run build

    # build the docker image, push to GitHub container registry
    - name: Build and Push Docker Image
      env:
        REGISTRY: ghcr.io
        OWNER: RobHolme
        IMAGE_NAME: cloud-region-api
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        target: final
        push: true
        tags: |
          $REGISTRY/$OWNER/$IMAGE_NAME:latest
        build-args: |
          NODE_ENV=production
  
