name: restart web app

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # 21:00Z every Saturday
    - cron: "0 21 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # restart app service
      - name: Push to repository
        run: |
          az login --service-principal --username ${{ secrets.APP_REGISTRATION_ID }} --password ${{ secrets.APP_REGISTRATION_CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
          az webapp restart --name cloud-region --resource-group Cloud-Region-API
          az logout