name: Weekly update of OCI JSON files

on:
  schedule:
    # 19:20Z every Saturday
    - cron: "20 19 * * 6"
  workflow_dispatch:

jobs:
  update-cloud-provider-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run update script
        shell: pwsh
        run: |
          ./update-cloudproviderjson.ps1 -CloudProvider OCI -Verbose
      - name: Push to repository
        continue-on-error: true
        run: |
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.EMAIL }}
          now=$(date)
          git add -A
          git commit -m "Auto update of OCI details JSON files on $now"
          git push
